[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
user_access = { path = "../user_access" }
common = { path = "../common" }
axum = { version = "0.4.5", features = ["ws", "headers"] }
tokio = { version = "1.15.0", features = ["full"] }
hyper = { version = "0.14.16", features = ["full"] }
tower = { version = "0.4.11", features = ["full"] }
tokio-stream = "0.1.8"
futures = "0.3.19"
once_cell = "1.9.0"
redis = { version = "0.21.5", features = ["tokio-comp"] }
deadpool-redis = { version = "0.10.2", features = ["serde"] }
xid = "1.0.0"
serde_json = "1.0.74"
serde-aux = "3.0.1"
config = "0.12.0"
deadpool-runtime = { version = "0.1.2", features = ["tokio_1"] }
oauth2 = "4.1.0"
base64 = "0.13.0"
hmac = "0.12.0"
hex = "0.4.3"
crypto-hash = "0.3.4"
regex = "1.5.4"
idna = "0.2.3"
argon2 = "0.3.2"
sha2 = "0.10.1"
rand_core = { version = "0.6.3", features = ["std"] }
hyper-tls = "0.5.0"
governor = "0.4.0"
reqwest = { version = "0.11.9", features = ["json"] }
rand = "0.8.4"
tokio-amqp = "2.0.0"

[dependencies.tower-http]
version = "0.2.0"
features = ['trace', 'compression-br', 'cors']

[dependencies.serde]
version = "1.0.133"
features = ['derive']

[dependencies.chrono]
version = "0.4.19"
features = ['serde']

[dependencies.rust_decimal]
version = "1.20.0"
features = ['db-tokio-postgres']

[dependencies.deadpool-postgres]
version = "0.10.1"
features = ['rt_tokio_1']

[dependencies.tokio-postgres]
version = "0.7.5"
features = ['with-chrono-0_4', 'with-serde_json-1']
